import { useState } from 'react';
import { Link } from 'react-router';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Check, RefreshCw, Sparkles, X } from 'lucide-react';
import { get, post } from '@/lib/api';
import { useI18n } from '@/lib/i18n';
import { Badge, Button, Card, EmptyState, ErrorState, PageHeader, Spinner, Tabs } from '@/components/ui';
import type { Recommendation } from '@shared/types';

const typeTone: Record<Recommendation['type'], 'brand' | 'warning' | 'info' | 'purple'> = { lesson: 'brand', practice: 'warning', resource: 'info', diksha: 'purple' };

export function RecommendationsPage() {
  const { t } = useI18n();
  const qc = useQueryClient();
  const [tab, setTab] = useState<'active' | 'all'>('active');
  const recs = useQuery({ queryKey: ['recommendations', tab], queryFn: () => get<{ recommendations: Recommendation[] }>(`/recommendations/me${tab === 'all' ? '?status=all' : ''}`).then((r) => r.recommendations) });
  const refresh = useMutation({ mutationFn: () => post('/recommendations/refresh'), onSuccess: () => qc.invalidateQueries({ queryKey: ['recommendations'] }) });
  const act = useMutation({ mutationFn: ({ id, action }: { id: string; action: 'done' | 'dismissed' }) => post(`/recommendations/${id}/${action}`), onSuccess: () => qc.invalidateQueries({ queryKey: ['recommendations'] }) });

  if (recs.isError) return <ErrorState error={recs.error} onRetry={() => recs.refetch()} />;
  const list = recs.data ?? [];
  const bySkill = list.reduce<Record<string, Recommendation[]>>((acc, r) => {
    const key = r.skillName ?? 'General';
    (acc[key] ??= []).push(r);
    return acc;
  }, {});

  return (
    <div>
      <PageHeader
        title={t('recommendations')}
        subtitle="Personalised next steps generated by the deterministic EduAdapt engine from your mastery data."
        actions={
          <>
            <Badge tone="brand">Adaptive Recommendation MVP</Badge>
            <Button variant="outline" size="sm" icon={<RefreshCw className="h-4 w-4" />} loading={refresh.isPending} onClick={() => refresh.mutate()}>
              Recompute
            </Button>
          </>
        }
      />
      <Tabs className="mb-4 w-fit" value={tab} onChange={setTab} tabs={[{ id: 'active', label: 'Active' }, { id: 'all', label: 'All' }]} />
      {recs.isLoading && <Spinner />}
      {!recs.isLoading && list.length === 0 && <EmptyState icon={<Sparkles className="h-8 w-8" />} title="No recommendations yet" description="Submit a practice set or quiz and the engine will build a plan around your weak areas." action={<Link to="/subjects" className="text-sm font-medium text-brand-700 hover:underline">Go to subjects →</Link>} />}
      <div className="space-y-6">
        {Object.entries(bySkill).map(([skill, items]) => (
          <Card key={skill}>
            <div className="border-b border-slate-100 px-5 py-3">
              <h2 className="text-sm font-semibold text-slate-900">
                {skill === 'General' ? 'Keep momentum' : `Weak skill: ${skill}`}
              </h2>
            </div>
            <ul className="divide-y divide-slate-100">
              {items.map((r) => (
                <li key={r.id} className="flex flex-col gap-2 px-5 py-3 sm:flex-row sm:items-center">
                  <div className="min-w-0 flex-1">
                    <div className="flex flex-wrap items-center gap-2">
                      <Link to={r.href} className="text-sm font-semibold text-slate-900 hover:text-brand-800 hover:underline">
                        {r.title}
                      </Link>
                      <Badge tone={typeTone[r.type]}>{r.type}</Badge>
                      {r.status !== 'active' && <Badge tone={r.status === 'done' ? 'success' : 'neutral'}>{r.status}</Badge>}
                      <span className="text-xs text-slate-400">priority {r.priority}</span>
                    </div>
                    <p className="mt-0.5 text-xs text-slate-600">{r.reason}</p>
                  </div>
                  {r.status === 'active' && (
                    <div className="flex shrink-0 items-center gap-1">
                      <Link to={r.href} className="inline-flex h-8 items-center rounded-lg bg-brand-600 px-3 text-xs font-medium text-white hover:bg-brand-700">
                        Open
                      </Link>
                      <button type="button" onClick={() => act.mutate({ id: r.id, action: 'done' })} className="rounded-md p-1.5 text-emerald-700 hover:bg-emerald-50" aria-label="Mark done" title="Mark done">
                        <Check className="h-4 w-4" />
                      </button>
                      <button type="button" onClick={() => act.mutate({ id: r.id, action: 'dismissed' })} className="rounded-md p-1.5 text-slate-500 hover:bg-slate-100" aria-label="Dismiss" title="Dismiss">
                        <X className="h-4 w-4" />
                      </button>
                    </div>
                  )}
                </li>
              ))}
            </ul>
          </Card>
        ))}
      </div>
    </div>
  );
}
